<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <Import Project="../Common.targets" />

    <PropertyGroup>
        <PackageProjectUrl>$(RepoUrl)</PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <IsPackable>false</IsPackable>

        <!-- Dalamud Packager properties for the plugin manifest -->
        <Author>UniversalConquistador</Author>
        <Name>Stagehand</Name>
        <MinimumDalamudVersion>14.0.0</MinimumDalamudVersion>
        <Punchline>All of creation, in the palm of your hand!</Punchline>
        <Description>Design layouts with extra scene objects in the game world. Perfect for decorating venues, immersive RP, or gposing backdrops! 
Use /stagehand to get started.</Description>
        <RepoUrl>https://github.com/universalconquistador/Stagehand</RepoUrl>
        <Tags>objects;weapons;lights;lighting;models;background;gpose</Tags>
        <CategoryTags></CategoryTags>
        <DalamudApiLevel>15</DalamudApiLevel>
        <LoadRequiredState>1</LoadRequiredState>
        <LoadSync>true</LoadSync>
        <CanUnloadAsync>false</CanUnloadAsync>
        <LoadPriority>1</LoadPriority>
        <ImageUrls></ImageUrls>
        <IconUrl>https://github.com/universalconquistador/Stagehand/releases/latest/download/icon.png</IconUrl>
        <Changelog></Changelog>

        <Use_Dalamud_FFXIVClientStructs Condition="'$(Configuration)'=='Debug'">false</Use_Dalamud_FFXIVClientStructs>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="Properties\**\*.json" />
    </ItemGroup>

    <ItemGroup>
      <None Include="ThreadLocalHelper.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />

        <ProjectReference Include="..\..\FFXIVClientStructs\FFXIVClientStructs\FFXIVClientStructs.csproj" Condition="'$(Configuration)'=='Debug'" Private="True" />
        <ProjectReference Include="..\..\FFXIVClientStructs\InteropGenerator.Runtime\InteropGenerator.Runtime.csproj" Condition="'$(Configuration)'=='Debug'" Private="True" />
        <ProjectReference Include="..\Stagehand.Api\Stagehand.Api.csproj" />
        <ProjectReference Include="..\Stagehand.Definitions\Stagehand.Definitions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Properties\Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Resources.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Properties\Resources.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>
</Project>
