name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      Solution_Name: Stagehand

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Download Dalamud
      run: curl --output latest.zip -L "https://goatcorp.github.io/dalamud-distrib/latest.zip"

    - name: Extract Dalamud
      run: unzip latest.zip -d /home/runner/dalamud-distrib

    - name: Restore dependencies
      run: dotnet restore Stagehand && dotnet restore Stagehand.Api && dotnet restore Stagehand.Definitions

    - name: Build with dotnet
      run: dotnet build Stagehand /p:Platform="x64" --no-restore --configuration Release && dotnet build Stagehand.Api /p:Platform="x64" --no-restore --configuration Release && dotnet build Stagehand.Definitions /p:Platform="x64" --no-restore --configuration Release
      env:
        DALAMUD_HOME: /home/runner/dalamud-distrib

    - name: Store Stagehand artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Stagehand
        path: ./Stagehand/bin/x64/Release/*
        if-no-files-found: error
        retention-days: 7

    - name: Store Stagehand.Api artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Stagehand.Api
        path: ./Stagehand.Api/bin/x64/Release/*
        if-no-files-found: error
        retention-days: 7

    - name: Store Stagehand.Definitions artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Stagehand.Definitions
        path: ./Stagehand.Definitions/bin/x64/Release/*
        if-no-files-found: error
        retention-days: 7
